name: 'info-from-package-json'
description: 'Reads and outputs some information from package.json'
author: 'Myrotvorets'
inputs:
  workingdir:
    required: false
    description: 'Directory with package.json (default: current working directory)'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
