name: 'Build and Test'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '12'

      - name: Update npm
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run all

  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v2.3.5
      - id: action
        uses: ./
      - run: 'echo -e "Name: ${{ steps.action.outputs.packageName }}\nVersion: ${{ steps.action.outputs.packageVersion }}\nDescription: ${{ steps.action.outputs.packageDescription }}"'
